# Translate the specified file into English and Japanese using a local LLM (processed line by line, with context)

# No default model is set (must be specified explicitly)

import argparse

# Main parser
epilog_text = """
Examples:
  # Run two-stage translation
  python translate.py phase1 input.txt -f French -t Spanish -o output.txt -m ollama:gemma3n:e4b
  python translate.py phase2a -o output.txt --draft-file output_draft.json -c ollama:qwen2.5:7b

  # Legacy processing
  python translate.py legacy input.txt -f French -t Spanish -o output.txt -m ollama:gemma3n:e4b

Detailed help:
  python translate.py phase1 -h       # Phase 1 options
  python translate.py phase2a -h      # Phase 2a (combined quality check + revision) options
  python translate.py legacy -h       # Legacy processing options
"""

parser = argparse.ArgumentParser(
    description="Multi-stage translation system",
    epilog=epilog_text,
    formatter_class=argparse.RawDescriptionHelpFormatter
)
subparsers = parser.add_subparsers(dest="command", help="Select the phase to run")

# Phase 1: initial translation
phase1_parser = subparsers.add_parser("phase1", help="Run the initial translation")
phase1_parser.add_argument("input_file", help="Text file to translate")
phase1_parser.add_argument("-f", "--from", dest="from_lang", required=True, help="Source language (e.g. English, French, Japanese)")
phase1_parser.add_argument("-t", "--to", dest="to_lang", required=True, help="Target language (e.g. English, French, Japanese)")
phase1_parser.add_argument("-o", "--output", dest="output_file", required=True, help="Output file name")
phase1_parser.add_argument("-m", "--model", required=True, help="Translation model (e.g. ollama:gemma3n:e4b)")

# Phase 2a: combined quality check + revision
phase2a_parser = subparsers.add_parser("phase2a", help="Run quality check and revision together")
phase2a_parser.add_argument("-o", "--output", dest="output_file", required=True, help="Output file name")
phase2a_parser.add_argument("--draft-file", required=True, help="Draft file generated by Phase 1")
phase2a_parser.add_argument("-c", "--checker-model", required=True, help="Model used for quality check and revision (e.g. ollama:qwen2.5:7b)")

# Phase 2: quality check (legacy, kept for compatibility)
phase2_parser = subparsers.add_parser("phase2", help="Run quality check (legacy)")
phase2_parser.add_argument("-o", "--output", dest="output_file", required=True, help="Output file name")
phase2_parser.add_argument("--draft-file", required=True, help="Draft file generated by Phase 1")
phase2_parser.add_argument("-c", "--checker-model", required=True, help="Model used for quality check (e.g. ollama:qwen2.5:7b)")

# Phase 3: apply revisions (legacy, kept for compatibility)
phase3_parser = subparsers.add_parser("phase3", help="Apply revisions (legacy)")
phase3_parser.add_argument("-o", "--output", dest="output_file", required=True, help="Output file name")
phase3_parser.add_argument("--draft-file", required=True, help="Draft file generated by Phase 1")
phase3_parser.add_argument("--check-file", required=True, help="Check file generated by Phase 2")
phase3_parser.add_argument("-m", "--model", required=True, help="Translation model (e.g. ollama:gemma3n:e4b)")

# Legacy integrated processing (backward compatibility)
legacy_parser = subparsers.add_parser("legacy", help="Legacy integrated processing (backward compatibility)")
legacy_parser.add_argument("input_file", help="Text file to translate")
legacy_parser.add_argument("-f", "--from", dest="from_lang", required=True, help="Source language (e.g. English, French, Japanese)")
legacy_parser.add_argument("-t", "--to", dest="to_lang", required=True, help="Target language (e.g. English, French, Japanese)")
legacy_parser.add_argument("-o", "--output", dest="output_file", required=True, help="Output file name")
legacy_parser.add_argument("-m", "--model", required=True, help="Translation model (e.g. ollama:gemma3n:e4b)")
legacy_parser.add_argument("-r", "--reasoning-level", type=int, default=2, choices=[0, 1, 2], help="Reasoning level: 0=no reasoning, 1=standard reasoning, 2=two-stage translation")

args = parser.parse_args()

# Show help if no command is specified
if not args.command:
    parser.print_help()
    exit(1)

# Set phase based on subcommand
if args.command == "phase1":
    args.phase = 1
elif args.command == "phase2a":
    args.phase = "2a"
elif args.command == "phase2":
    args.phase = 2
elif args.command == "phase3":
    args.phase = 3
else:  # legacy
    args.phase = None

# Read the file only for Phase 1 and legacy
if args.phase == 1 or args.command == "legacy":
    with open(args.input_file, "r", encoding="utf-8") as f:
        lines = f.readlines()
else:
    # Phase 2a/2/3 process from JSON, so lines are not needed
    lines = []

import json
import re
from pydantic import BaseModel, Field
from llm7shi.compat import generate_with_schema
from llm7shi import create_json_descriptions_prompt
from tqdm import tqdm

# Retrieve language settings (used for Phase 2/3)
from_lang = getattr(args, 'from_lang', None)
to_lang = getattr(args, 'to_lang', None)

# Branch for phase-based processing or reasoning level 3
if args.phase or (hasattr(args, 'reasoning_level') and args.reasoning_level == 3):
    # The schema class is created dynamically later (after metadata is obtained)
    pass

# Legacy level-based processing
elif hasattr(args, 'reasoning_level') and args.reasoning_level == 0:
    class Translation(BaseModel):
        translation: str = Field(description=f"{args.from_lang} to {args.to_lang} translation result")
elif hasattr(args, 'reasoning_level') and args.reasoning_level == 1:
    class Translation(BaseModel):
        reasoning: str = Field(description=f"Carefully analyze the meaning and context of the original {args.from_lang} text. Consider cultural nuances, idiomatic expressions, and the speaker's intent. Evaluate different possible translation choices and explain your reasoning for selecting the most appropriate words and phrasing for the {args.to_lang} translation.")
        translation: str = Field(description=f"{args.from_lang} to {args.to_lang} translation result")
elif hasattr(args, 'reasoning_level') and args.reasoning_level == 2:
    class Translation(BaseModel):
        draft_translation: str = Field(description=f"First draft translation from {args.from_lang} to {args.to_lang}")
        quality_check: str = Field(description=f"Analyze the draft translation for errors, mistranslations, language mixing, unnatural expressions, and cultural appropriateness. Check specifically that: 1) The text is completely translated into {args.to_lang}, 2) No {args.from_lang} words or expressions remain untranslated, 3) The translation is natural and appropriate. Identify specific issues and suggest improvements.")
        translation: str = Field(description=f"Final polished {args.from_lang} to {args.to_lang} translation based on the quality check feedback")

def normalize(text):
    # Convert all characters with ord(ch)<32 to spaces
    normalized = ''.join(' ' if ord(ch) < 32 else ch for ch in text)
    # Collapse consecutive spaces into one
    normalized = re.sub(r' +', ' ', normalized)
    return normalized.strip()

def load_phase_data(file_path):
    """Load inter-phase data"""
    if not file_path:
        return {}, []
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
            if isinstance(data, dict) and 'metadata' in data and 'results' in data:
                # results is always returned as a list
                return data['metadata'], data['results']
            else:
                # Compatibility with the old format
                return {}, data if isinstance(data, list) else []
    except FileNotFoundError:
        print(f"Warning: file {file_path} not found")
        return {}, []

def save_phase_data(data, file_path, metadata=None):
    """Save inter-phase data"""
    # Convert to list form if data is a dict
    if isinstance(data, dict):
        results_list = []
        for line_key, item_data in data.items():
            if isinstance(item_data, dict) and 'speaker' in item_data:
                results_list.append(item_data)
            else:
                # Compatibility handling for the old format
                results_list.append(item_data)
        data = results_list

    output_data = {
        'metadata': metadata or {},
        'results': data
    }
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(output_data, f, ensure_ascii=False, indent=2)

def get_phase_file_path(base_path, phase):
    """Generate the file path for each phase"""
    base = base_path.rsplit('.', 1)[0]
    if phase == 1:
        return f"{base}_draft.json"
    elif phase == "2a":
        return f"{base}_final.json"
    elif phase == 2:
        return f"{base}_check.json"
    else:
        return base_path

# Prepare phase-specific processing
if args.phase or (hasattr(args, 'reasoning_level') and args.reasoning_level == 3):
    if args.phase == 1:
        # Phase 1: initial translation
        class DraftTranslation(BaseModel):
            translation: str = Field(description=f"Direct translation from {args.from_lang} to {args.to_lang}")

        current_schema = DraftTranslation
        current_model = args.model
        json_descriptions = create_json_descriptions_prompt(DraftTranslation)
    elif args.phase == "2a":
        # Phase 2a: combined quality check + revision
        draft_metadata, draft_data = load_phase_data(args.draft_file)
        # Restore language settings from metadata
        if 'from_lang' in draft_metadata:
            args.from_lang = draft_metadata['from_lang']
        if 'to_lang' in draft_metadata:
            args.to_lang = draft_metadata['to_lang']

        # Define the schema after obtaining language settings
        class QualityCheckAndRevision(BaseModel):
            quality_assessment: str = Field(description=f"Analyze this {args.from_lang} to {args.to_lang} translation for errors, mistranslations, language mixing, unnatural expressions, and cultural appropriateness. Check specifically that: 1) The text is completely translated into {args.to_lang}, 2) No {args.from_lang} words or expressions remain untranslated, 3) The translation is natural and appropriate. List specific issues found.")
            improvement_suggestions: str = Field(description=f"Provide specific suggestions for improving the translation quality")
            improved_translation: str = Field(description=f"Based on the quality assessment and improvement suggestions above, provide an improved {args.from_lang} to {args.to_lang} translation that addresses all identified issues")
        
        current_schema = QualityCheckAndRevision
        current_model = args.checker_model
        json_descriptions = create_json_descriptions_prompt(QualityCheckAndRevision)
    elif args.phase == 2:
        # Phase 2: quality check (legacy, kept for compatibility)
        draft_metadata, draft_data = load_phase_data(args.draft_file)
        # Restore language settings from metadata
        if 'from_lang' in draft_metadata:
            args.from_lang = draft_metadata['from_lang']
        if 'to_lang' in draft_metadata:
            args.to_lang = draft_metadata['to_lang']

        # Define the schema after obtaining language settings
        class QualityCheck(BaseModel):
            quality_assessment: str = Field(description=f"Analyze this {args.from_lang} to {args.to_lang} translation for errors, mistranslations, language mixing, unnatural expressions, and cultural appropriateness. Check specifically that: 1) The text is completely translated into {args.to_lang}, 2) No {args.from_lang} words or expressions remain untranslated, 3) The translation is natural and appropriate. List specific issues found.")
            improvement_suggestions: str = Field(description=f"Provide specific suggestions for improving the translation quality")
            needs_revision: bool = Field(description="True if the translation needs revision, False if it's acceptable as-is")
        
        current_schema = QualityCheck
        current_model = args.checker_model
        json_descriptions = create_json_descriptions_prompt(QualityCheck)
    elif args.phase == 3:
        # Phase 3: apply revisions
        draft_metadata, draft_data = load_phase_data(args.draft_file)
        check_metadata, check_data = load_phase_data(args.check_file)
        # Restore language settings from metadata
        if 'from_lang' in draft_metadata:
            args.from_lang = draft_metadata['from_lang']
        if 'to_lang' in draft_metadata:
            args.to_lang = draft_metadata['to_lang']

        # Define the schema after obtaining language settings
        class RevisedTranslation(BaseModel):
            improved_translation: str = Field(description=f"Improved {args.from_lang} to {args.to_lang} translation incorporating the quality check feedback and suggestions")

        current_schema = RevisedTranslation
        current_model = args.model
        json_descriptions = create_json_descriptions_prompt(RevisedTranslation)
    else:
        # reasoning_level == 3: automatic three-stage execution
        pass
else:
    # Legacy processing
    current_schema = Translation
    current_model = args.model
    json_descriptions = create_json_descriptions_prompt(Translation)

context_history = []  # for keeping context

# Count the lines to translate in advance
translation_lines = [line for line in lines if line.strip() and ":" in line.strip()]

def create_phase_prompt(phase, speaker, text, line_key=None):
    """Create a prompt for each phase"""
    if phase == 1 or (not args.phase and hasattr(args, 'reasoning_level') and args.reasoning_level != 3):
        # Phase 1 or legacy processing: translation
        return f"Translate the following {args.from_lang} text spoken by {speaker} into {args.to_lang}:\n{text}"
    elif phase == "2a":
        # Phase 2a: combined quality check + revision
        draft_translation = None
        original_text = None

        if isinstance(draft_data, dict) and line_key and line_key in draft_data:
            # Dict form
            draft_translation = draft_data[line_key]['translation']
            original_text = draft_data[line_key]['original']
        elif isinstance(draft_data, list):
            # List form
            for item in draft_data:
                if isinstance(item, dict) and 'speaker' in item and 'original' in item:
                    if f"{item['speaker']}:{item['original']}" == line_key:
                        draft_translation = item['translation']
                        original_text = item['original']
                        break
        
        if draft_translation and original_text:
            return f"""Original {args.from_lang} text: {original_text}

Draft translation: {draft_translation}

Please analyze this translation for quality issues and provide an improved version. Pay special attention to:
1. Ensure no {args.from_lang} words or expressions remain untranslated
2. Check for mistranslations and unnatural expressions
3. Verify cultural appropriateness and context accuracy
4. Provide specific improvement suggestions
5. Generate a final improved translation that addresses all identified issues"""
        return f"No draft translation found for: {text}"
    elif phase == 2:
        # Phase 2: quality check (legacy, kept for compatibility)
        draft_translation = None
        original_text = None

        if isinstance(draft_data, dict) and line_key and line_key in draft_data:
            # Dict form
            draft_translation = draft_data[line_key]['translation']
            original_text = draft_data[line_key]['original']
        elif isinstance(draft_data, list):
            # List form
            for item in draft_data:
                if isinstance(item, dict) and 'speaker' in item and 'original' in item:
                    if f"{item['speaker']}:{item['original']}" == line_key:
                        draft_translation = item['translation']
                        original_text = item['original']
                        break
        
        if draft_translation and original_text:
            return f"Original {args.from_lang} text: {original_text}\nDraft translation: {draft_translation}\n\nAnalyze this translation for quality issues."
        return f"No draft translation found for: {text}"
    elif phase == 3:
        # Phase 3: apply revisions
        draft_translation = None
        original_text = None
        quality_assessment = None
        improvement_suggestions = None

        # Search draft_data (always a list)
        current_draft_idx = None
        for draft_idx, draft_item in enumerate(draft_data):
            if (isinstance(draft_item, dict) and 'speaker' in draft_item and 'original' in draft_item and
                f"{draft_item['speaker']}:{draft_item['original']}" == line_key):
                draft_translation = draft_item['translation']
                original_text = draft_item['original']
                current_draft_idx = draft_idx
                break

        # Search check_data (always a list, matched by index)
        if current_draft_idx is not None and current_draft_idx < len(check_data):
            check_item = check_data[current_draft_idx]
            if isinstance(check_item, dict):
                quality_assessment = check_item.get('quality_assessment')
                improvement_suggestions = check_item.get('improvement_suggestions')
        
        if draft_translation and original_text and quality_assessment:
            return f"""Original {args.from_lang} text: {original_text}

Draft translation: {draft_translation}

Quality assessment: {quality_assessment}

Improvement suggestions: {improvement_suggestions}

Based on the quality assessment and improvement suggestions above, please revise the draft translation. Pay special attention to:
1. Ensure no {args.from_lang} words or expressions remain untranslated
2. Replace unnatural expressions with natural {args.to_lang} phrasing
3. Improve vocabulary choices and expressions to fit the context
4. Address specific issues identified in the quality check

Provide the improved translation."""
        return f"No quality check data found for: {text}"

# For storing phase data
phase_results = {}

# Phase-specific processing
if args.phase in ["2a", 2, 3]:
    # Phase 2a/2/3: process from JSON data
    data_source = draft_data if args.phase in ["2a", 2] else draft_data

    # Generate processing items depending on data format
    processing_items = []
    if isinstance(data_source, dict):
        # Dict form (legacy format)
        processing_items = [(line_key, data['original'], data['speaker']) for line_key, data in data_source.items()]
    elif isinstance(data_source, list):
        # List form (new format)
        for data in data_source:
            if isinstance(data, dict) and 'speaker' in data and 'original' in data:
                line_key = f"{data['speaker']}:{data['original']}"
                processing_items.append((line_key, data['original'], data['speaker']))
else:
    # Phase 1/legacy: process from file
    processing_items = []
    for line in lines:
        line = line.strip()
        if ":" not in line:
            continue
        speaker, text = line.split(":", 1)
        speaker = speaker.strip()
        text = text.strip()
        line_key = f"{speaker}:{text}"
        processing_items.append((line_key, text, speaker))

# Run processing
for line_key, text, speaker in tqdm(processing_items, desc=f"Phase {args.phase or 'combined'} processing"):
    print()
    print(f"{speaker}: {text}")

    # Create phase-specific prompt
    prompt = create_phase_prompt(args.phase, speaker, text, line_key)

    # Prepare message array
    messages = [prompt, json_descriptions]

    # Add phase-specific context (except Phase 3)
    if args.phase not in [3] and context_history:
        context_lines = []
        context_lines.append("Previous conversation context:")
        context_lines.append("")
        for ctx in context_history[-5:]:
            context_lines.append(f"Original: {ctx['speaker']}: {ctx['original']}")
            context_lines.append(f"Translation: {ctx['speaker']}: {ctx['translation']}")
            context_lines.append("")
        context = "\n".join(context_lines)
        messages.insert(0, context)  # Insert context at the beginning

    # Run the actual processing
    for j in range(5):
        if j:
            print("Retry:", j)
        try:
            result = generate_with_schema(
                messages,
                schema=current_schema,
                model=current_model,
                max_length=4096,
                show_params=True,
            )
            parsed = json.loads(result.text.strip())
            break
        except Exception as e:
            if j < 4:
                print(e)
            else:
                raise
    
    # Process results per phase
    if args.phase == 1:
        # Phase 1: save the translation result
        translated_text = normalize(parsed['translation'])
        phase_results[line_key] = {
            'original': text,
            'translation': translated_text,
            'speaker': speaker
        }
        context_history.append({
            'speaker': speaker,
            'original': text,
            'translation': translated_text
        })
    elif args.phase == "2a":
        # Phase 2a: save the combined quality-check + revision result
        translated_text = normalize(parsed['improved_translation'])
        phase_results[line_key] = {
            'original': text,
            'translation': translated_text,
            'speaker': speaker,
            'quality_assessment': parsed['quality_assessment'],
            'improvement_suggestions': parsed['improvement_suggestions']
        }
        context_history.append({
            'speaker': speaker,
            'original': text,
            'translation': translated_text
        })
    elif args.phase == 2:
        # Phase 2: save the quality check result (legacy, kept for compatibility)
        phase_results[line_key] = {
            'quality_assessment': parsed['quality_assessment'],
            'improvement_suggestions': parsed['improvement_suggestions'],
            'needs_revision': parsed['needs_revision']
        }
    elif args.phase == 3:
        # Phase 3: save the revised translation
        translated_text = normalize(parsed['improved_translation'])
        phase_results[line_key] = {'translation': translated_text}
        context_history.append({
            'speaker': speaker,
            'original': text,
            'translation': translated_text
        })
    else:
        # Legacy processing
        if 'translation' in parsed:
            translated_text = normalize(parsed['translation'])
        elif 'draft_translation' in parsed:
            translated_text = normalize(parsed['translation'])
        else:
            translated_text = normalize(str(parsed))
        
        context_history.append({
            'speaker': speaker,
            'original': text,
            'translation': translated_text
        })

# Save results
if args.phase:
    # Save phase-specific results as JSON
    phase_file = get_phase_file_path(args.output_file, args.phase)

    # Also save metadata for Phase 1
    metadata = {}
    if args.phase == 1:
        metadata = {
            'from_lang': args.from_lang,
            'to_lang': args.to_lang,
            'input_file': args.input_file,
            'model': args.model
        }

    save_phase_data(phase_results, phase_file, metadata)
    print(f"Phase {args.phase} complete: {phase_file}")

    if args.phase in [1, "2a", 3]:
        # Phases 1, 2a, and 3 also output the translation result as text
        with open(args.output_file, "w", encoding="utf-8") as f:
            for ctx in context_history:
                f.write(f"{ctx['speaker']}: {ctx['translation']}\n")
        print(f"Translation result: {args.output_file}")
else:
    # Legacy processing: save to a text file
    with open(args.output_file, "w", encoding="utf-8") as f:
        for ctx in context_history:
            f.write(f"{ctx['speaker']}: {ctx['translation']}\n")
    print(f"Translation complete: {args.from_lang} → {args.to_lang} ({args.output_file})")
